"""duration_quality_of_life

Revision ID: 46eb91fef40a
Revises: a2cab60129c2
Create Date: 2026-05-28 00:56:56.851657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46eb91fef40a'
down_revision: Union[str, Sequence[str], None] = 'a2cab60129c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expiry_duration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False), # Used for mapping the obsolete "duration" enum with the new "expires_at" column.
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('is_enabled',sa.Boolean(), nullable=False, server_default=sa.true()),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.bulk_insert(
        sa.table(
            'expiry_duration',
            sa.column('name', sa.String),
            sa.column('code', sa.String),
            sa.column('days', sa.Integer),
        ),
        [
            {"name": "1 Day", "code": "oneDay", "days": 1},
            {"name": "10 Days", "code": "TenDays", "days": 10},
            {"name": "30 Days", "code": "ThirtyDays", "days": 30},
        ]
    )

    # Expires_at column. It's populated by api at the moment of insertion.
    op.add_column('pasted', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.execute("""
    UPDATE pasted
    SET expires_at = NOW() + INTERVAL '30 days'
    WHERE expires_at IS NULL
    """)
    op.alter_column(
        'pasted',
        'expires_at',
        nullable=False
    )


    # One time paste functionality.
    op.add_column('pasted', sa.Column('is_one_time', sa.Boolean(), nullable=False,server_default=sa.false()))

    op.alter_column('pasted', 'duration', nullable=True) # Duration enum will be obsolete.
    op.create_index(op.f('ix_pasted_is_one_time'), 'pasted', ['is_one_time'], unique=False)
    ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pasted_is_one_time'), table_name='pasted')
    op.drop_column('pasted', 'is_one_time')
    op.drop_column('pasted', 'expires_at')
    op.alter_column('pasted', 'duration', nullable=False)
    op.drop_table('expiry_duration')
    # ### end Alembic commands ###
